In [1]:
import pandas as pd
df= pd.read_csv('housing.csv')

In [4]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [7]:
df.size

206400

In [8]:
df.shape

(20640, 10)

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [10]:
df['total_bedrooms'].mean()

537.8705525375618

In [11]:
df["total_bedrooms"].fillna(537,inplace=True)

In [12]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [24]:
X=pd.DataFrame(df["median_income"])
y=pd.DataFrame(df["median_house_value"])

In [26]:
X.size

20640

In [27]:
y.size

20640

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=1)

In [29]:
X_train.shape

(16512, 1)

In [30]:
y_train.shape

(16512, 1)

In [31]:
lr = LinearRegression()

In [34]:
model = lr.fit(X_train,y_train)

In [35]:
lr.intercept_

array([44721.83362107])

In [36]:
lr.coef_

array([[42055.4573838]])

In [37]:
y_test

median_house_value
4712             355000.0
2151              70700.0
15927            229400.0
82               112500.0
8161             225400.0
...                   ...
2319              68200.0
5341             225000.0
16888            350000.0
6823             227300.0
11878            141700.0

[4128 rows x 1 columns]

In [38]:
predictions = lr.predict(X_test)

In [39]:
predictions

array([[181402.07011843],
       [127924.35050918],
       [213498.79519375],
       ...,
       [257017.7824945 ],
       [249742.18836711],
       [158498.66802721]])

In [40]:
from sklearn import metrics
import numpy as np

In [41]:
print("MAE",metrics.mean_absolute_error(y_test,predictions))

MAE 62184.11511576648


In [42]:
print("MsE",metrics.mean_squared_error(y_test,predictions))

MsE 6926929696.091081


In [43]:
print("RMSE",np.sqrt(metrics.mean_squared_error(y_test,predictions)))

RMSE 83228.17849797675
