In [2]:
from sklearn.datasets import load_boston
boston = load_boston()

In [3]:
type(boston)

sklearn.utils.Bunch

In [4]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [ ]:
print(boston)

In [5]:
boston['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
boston['data'].shape

(506, 13)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(boston['data'],boston['target'],test_size=0.30)

In [9]:
X_train.shape

(354, 13)

In [10]:
y_train.shape

(354,)

In [11]:
lr = LinearRegression()

In [12]:
model = lr.fit(X_train,y_train)


In [13]:
lr.score(X_test,y_test)


0.716403691490276

In [14]:
lr.intercept_



31.671390036015325

In [15]:
lr.coef_


array([-1.08950411e-01,  5.40705268e-02,  3.21143746e-02,  2.23540075e+00,
       -1.41086822e+01,  3.90730512e+00, -1.19285002e-02, -1.37733429e+00,
        3.17641008e-01, -1.28244957e-02, -9.09252053e-01,  1.26029891e-02,
       -4.87827566e-01])

In [16]:
y_test

array([12.1, 29.1, 20. , 15.1, 17.5, 13.4, 12.5, 33.2, 20.5, 14.4, 24.8,
       22. , 15.6, 10.5,  8.1, 24.1, 19.9, 22.2, 20. , 21.7, 19.1, 17.1,
       30.3, 24.7, 13.5, 21.4, 23.8,  8.7, 50. , 22.9, 16.6, 23. , 16.7,
       31.7, 23.9, 19.3, 21.4, 45.4, 31.2, 50. , 20.2, 17.9, 12.6, 29.1,
       28.4, 39.8, 26.4, 19.2, 46.7, 22.9, 19.9, 50. , 18.1, 27.1, 50. ,
       20.3, 13.1, 23.8, 20.3, 44.8, 23. , 37.3, 24.8, 25. , 13.6, 22.6,
       48.3, 23.3, 37.2, 21.8, 22. , 23.5, 17.5,  7. , 27.9, 17.8, 21.7,
       50. , 17.5, 20.7, 33.1, 24.5, 29.6, 21.2, 13.4, 24.1,  5.6, 22.6,
       26.2, 18.4, 20.4, 19.7, 23.1, 22.3, 33.8, 19.9, 18. , 29.9, 17.8,
       17.3, 24.6, 14.5, 25.1, 24. , 20.3, 26.6, 27.9, 23.8, 13.2, 32. ,
       31.5, 26.4, 22.2, 12.7, 11.3, 15.6, 23.7, 22.6, 28.7, 24.4, 13. ,
       23.1, 22.5, 19.5, 25. , 11.7, 28.2, 21.9, 22.1, 25. ,  6.3, 22.6,
       26.6, 20. , 17.8, 18.5, 14. , 19. ,  8.4, 21.1, 35.4,  8.3, 14.6,
       13.5, 20.8, 22.9, 50. , 43.5, 19.6, 20.1, 50

In [17]:
predictions = lr.predict(X_test)


In [18]:
predictions


array([18.54967897, 31.7093652 , 19.00927041, 17.46963466, 16.52369211,
       13.1910421 , 19.67550538, 31.60700574, 19.6476294 ,  9.0801164 ,
       26.08113074, 27.51534775, 15.48257077,  6.6037181 ,  3.57886397,
       25.64328187, 18.40723341, 19.56295669, 16.19516228, 23.00126771,
       23.60945014, 17.83642954, 32.8311697 , 24.89753534, 13.09735783,
       23.68021956, 25.5486016 ,  8.29687035, 40.58831822, 22.93625757,
       17.72033262, 19.85741252, 19.61661737, 32.65846051, 26.6032833 ,
       21.06221886, 21.78064476, 38.24396484, 29.03434685, 43.53194429,
       22.7350616 ,  0.84181431, 18.56781609, 30.47141323, 27.85166002,
       34.01985457, 29.15120301, 19.89144485, 35.53584967, 28.85687612,
       19.3595003 , 25.26132581, 17.2746275 , 27.08049016, 36.46428811,
       22.25547889, 20.55831015, 24.74138973, 19.45544337, 37.71879123,
       28.72433245, 34.83671277, 27.36253602, 24.45309659, 12.2993957 ,
       22.92079818, 36.66718136, 28.39234634, 32.37552808, 20.66

In [19]:
from sklearn import metrics
import numpy as np

In [20]:
print("MAE",metrics.mean_absolute_error(y_test,predictions))


MAE 3.466725707715881


In [21]:
print("MsE",metrics.mean_squared_error(y_test,predictions))


MsE 26.277391239502993


In [22]:
print("RMsE",np.sqrt(metrics.mean_squared_error(y_test,predictions)))


RMsE 5.126147797274577


In [23]:
lr.score(X_test,y_test)

0.716403691490276